---
repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["o3research"]
  - repo: https://github.com/igorshubovych/markdownlint-cli2
    rev: v0.7.0
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint-cli2
        language: node
        types: [markdown]
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types: [yaml]
      - id: validate-golden-prompts
        name: validate-golden-prompts
        entry: bash scripts/validate_golden_prompts.sh
        language: system
        pass_filenames: false
      - id: unit-tests
        name: unit-tests
        entry: python -m unittest discover tests
        language: system
        pass_filenames: false
