---
# Default configuration for ADK agents
prompt_version: 4.0.0
routing_weight: 1      # weight for ConfigAgent routing
log_level: INFO        # default logging level
event_bus: async       # event bus type (async or sync)
max_queue_size: 100    # max event queue length
