# Default configuration for ADK agents
prompt_version: 3.5.7  # prompt kernel version used across agents
routing_weight: 1      # weight for ConfigAgent routing
log_level: INFO        # default logging level (DEBUG, INFO, ERROR)
event_bus: async       # event bus type (`async` or `sync`)
max_queue_size: 100    # max event queue length for async bus
