---
name: Deploy Vertex AI Agent

'on':
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.adk.json'
      - 'flows/**'
      - '.github/workflows/deploy_vertex_ai.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy agent
        run: gcloud ai agents deploy --config .adk.json
